spring:
  application:
    name: lending-service
    version: ${version}

server:
  servlet:
    context-path: /lending-service

management:
  server:
    port: 8081
    servlet:
      context-path: /

info:
  app:
    name: \${spring.application.name}
    version: \${spring.application.version}

---
spring:
  profiles: local
  datasource:
    url: jdbc:h2:mem:userdb
    username: sa
    password:
  sleuth:
    sampler:
      probability: 100

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate.ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
      javax.persistence:
        schema-generation:
          create-source=metadata
          scripts.action=create
          scripts.create-target=build/create.sql

server:
  port:
    7004

management:
  server:
    port: 7005
