export const LOGOUT = 'LOGOUT';
export const SET_USER = 'SET_USER';
export const SET_ACCOUNT = 'SET_ACCOUNT';
export const SET_CREDIT_DECISION = 'SET_CREDIT_DECISION';
export const SET_ACCOUNT_BALANCE = 'SET_ACCOUNT_BALANCE';
